services:
    sylius_consumer_plugin.denormalizer.association_type:
        class: Sylake\SyliusConsumerPlugin\Denormalizer\AssociationTypeUpdatedDenormalizer
        public: true
        tags:
            - { name: rabbitmq_simplebus.amqp_denormalizer }
        arguments: ['@monolog.logger.queue']
    sylius_consumer_plugin.projector.association_type:
        class: Sylake\SyliusConsumerPlugin\Projector\AssociationTypeProjector
        public: true
        tags:
            - { name: event_subscriber, subscribes_to: Sylake\SyliusConsumerPlugin\Event\AssociationTypeUpdated, method: __invoke }
        arguments: ['@sylius.factory.product_association_type', '@sylius.repository.product_association_type', '@monolog.logger.queue']
