services:
    sylius_consumer_plugin.doctrine_orm_mapping_class_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        public: false
        arguments: [Sylake\SyliusConsumerPlugin\Entity\AkeneoAttributeOption]
        factory: ['@doctrine.orm.default_entity_manager', getClassMetadata]
    sylius_consumer_plugin.denormalizer.attribute_option:
        class: Sylake\SyliusConsumerPlugin\Denormalizer\AttributeOptionUpdatedDenormalizer
        public: true
        tags:
        - { name: rabbitmq_simplebus.amqp_denormalizer }
    sylius_consumer_plugin.projector.attribute_option:
        class: Sylake\SyliusConsumerPlugin\Projector\AttributeOptionProjector
        public: true
        tags:
        - { name: event_subscriber, subscribes_to: Sylake\SyliusConsumerPlugin\Event\AttributeOptionUpdated, method: __invoke }
        arguments: ['@sylake_sylius_consumer.repository.akeneo_attribute_option', '@monolog.logger']
    sylake_sylius_consumer.repository.akeneo_attribute_option:
        class: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '@sylius_consumer_plugin.doctrine_orm_mapping_class_metadata']
