services:
    sylius_consumer_plugin.denormalizer.family:
        class: Sylake\SyliusConsumerPlugin\Denormalizer\FamilyUpdatedDenormalizer
        public: true
        tags:
            - { name: rabbitmq_simplebus.amqp_denormalizer }
    sylius_consumer_plugin.projector.family:
        class: Sylake\SyliusConsumerPlugin\Projector\FamilyProjector
        public: true
        tags:
            - { name: event_subscriber, subscribes_to: Sylake\SyliusConsumerPlugin\Event\FamilyUpdated, method: __invoke }
        arguments: ['@sylius.repository.product_attribute', '@sylake_sylius_consumer.repository.akeneo_attribute_option', '@sylius.factory.product_attribute', '@monolog.logger']
